[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
# Use Solidity 0.8.20 for OpenZeppelin v5.x compatibility
solc_version = '0.8.20'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config