name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Lint JavaScript
        run: |
          if [ -f .eslintrc.js ] || [ -f .eslintrc.json ]; then
            npx eslint .
          else
            echo 'No ESLint config found, skipping lint.'
          fi

      - name: Test JavaScript
        run: npm test

      - name: Audit npm dependencies
        run: npm audit --audit-level=moderate

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: 'latest'

      - name: Lint Solidity
        run: forge fmt --check

      - name: Test Solidity
        run: forge test --root ./TestAgent

      - name: Audit Solidity (MythX)
        run: echo 'Integrate MythX or Slither here if needed.'
        # Example: slither .
        # Requires additional setup
