name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Lint JavaScript
        run: |
          if [ -f .eslintrc.js ] || [ -f .eslintrc.json ]; then
            npx eslint . --max-warnings 0 || echo 'Lint issues found but continuing...'
          else
            echo 'No ESLint config found, skipping lint.'
          fi

      - name: Test JavaScript
        run: npm test

      - name: Audit npm dependencies
        run: |
          # Try audit with timeout to prevent hanging
          if timeout 45 npm audit --audit-level=moderate; then
            echo "✅ No vulnerabilities found"
          else
            echo "⚠️ Audit service unavailable or vulnerabilities found, but continuing..."
          fi
        continue-on-error: true

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: 'nightly'
        continue-on-error: true

      - name: Lint Solidity Templates
        run: |
          if command -v forge &> /dev/null; then
            forge fmt --check --root ./agent-template || echo 'Solidity linting skipped'
          else
            echo 'Foundry not available, skipping Solidity lint'
          fi
        continue-on-error: true

      # Run setup.sh in all agent templates to ensure dependencies are installed
      - name: Setup agent-template
        run: |
          cd agent-template && bash setup.sh
        continue-on-error: true
      - name: Setup defi-agent
        run: |
          cd templates/defi-agent && bash setup.sh
        continue-on-error: true
      - name: Setup nft-agent
        run: |
          cd templates/nft-agent && bash setup.sh
        continue-on-error: true
      - name: Setup yield-agent
        run: |
          cd templates/yield-agent && bash setup.sh
        continue-on-error: true

      - name: Install Forge Dependencies
        run: |
          if command -v forge &> /dev/null; then
            cd agent-template && forge install || echo 'Forge install skipped'
          else
            echo 'Foundry not available, skipping forge install'
          fi
        continue-on-error: true

      - name: Test Solidity Templates
        run: |
          if command -v forge &> /dev/null; then
            forge test --root ./agent-template || echo 'Solidity tests skipped'
          else
            echo 'Foundry not available, skipping Solidity tests'
          fi
        continue-on-error: true
