name: Deploy Solidity

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: 'nightly'

      - name: "Build Solidity contracts"
        run: forge build --root ./agent-template

      - name: "Debug: list files"
        run: |
          echo "PWD: $(pwd)"
          ls -la
          ls -la agent-template || true
          ls -la agent-template/script || true

      - name: "Show Deploy.s.sol"
        run: sed -n '1,200p' agent-template/script/Deploy.s.sol || true

      - name: "Check Deploy.s.sol exists"
        run: test -f agent-template/script/Deploy.s.sol || (echo "Deploy.s.sol missing" && exit 1)

      - name: "Check PRIVATE_KEY secret present"
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          if [ -z "$PRIVATE_KEY" ]; then
            echo "ERROR: PRIVATE_KEY is empty or not set in secrets"
            exit 1
          else
            echo "PRIVATE_KEY is present (value not shown)"
          fi

      - name: "Deploy to Testnet/Mainnet"
        working-directory: ./agent-template
        env:
          SOMNIA_RPC_URL: ${{ secrets.SOMNIA_RPC_URL }}
          # Ensure PRIVATE_KEY has 0x prefix so vm.envUint can parse it
          PRIVATE_KEY: ${{ format('0x{}', secrets.PRIVATE_KEY) }}
        run: |
          # run from inside agent-template to avoid path/root mismatches
          forge script script/Deploy.s.sol:Deploy --rpc-url $SOMNIA_RPC_URL --private-key $PRIVATE_KEY --broadcast --verify --root .

      - name: "Verify contract (optional)"
        run: echo 'Contract verification not implemented. Add forge verify-contract command here.'