name: Deploy Solidity

on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: 'nightly'

      - name: Install Forge Dependencies
        run: |
          cd agent-template
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git init
          git add .
          git commit -m "Initial commit" || true
          forge install foundry-rs/forge-std || echo 'Forge install completed'
          ls -la lib/ || echo 'No lib directory'

      - name: "Build Solidity contracts"
        run: forge build --root ./agent-template

      - name: "Debug: list files"
        run: |
          echo "PWD: $(pwd)"
          ls -la
          ls -la agent-template || true
          ls -la agent-template/script || true

      - name: "Show Deploy.s.sol"
        run: sed -n '1,200p' agent-template/script/Deploy.s.sol || true

      - name: "Check Deploy.s.sol exists"
        run: test -f agent-template/script/Deploy.s.sol || (echo "Deploy.s.sol missing" && exit 1)

      - name: "Check PRIVATE_KEY secret present"
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          if [ -z "$PRIVATE_KEY" ]; then
            echo "ERROR: PRIVATE_KEY is empty or not set in secrets"
            exit 1
          else
            echo "PRIVATE_KEY is present (value not shown)"
          fi

      - name: "Deploy to Testnet/Mainnet"
        working-directory: ./agent-template
        env:
          SOMNIA_RPC_URL: ${{ secrets.SOMNIA_RPC_URL }}
          # Ensure PRIVATE_KEY has 0x prefix so vm.envUint can parse it
          PRIVATE_KEY: ${{ format('0x{0}', secrets.PRIVATE_KEY) }}
        run: |
          # run from inside agent-template to avoid path/root mismatches
          set -euo pipefail
          echo "Installing jq for JSON inspection..."
          sudo apt-get update -y && sudo apt-get install -y jq || true

          echo "Running forge create..."
          # Run forge create but don't let a non-zero exit immediately stop our diagnostics
          set +e
          forge create src/AgentContract.sol:AgentContract --rpc-url "$SOMNIA_RPC_URL" --private-key "$PRIVATE_KEY" --broadcast --gas-limit 13000000 --legacy
          rc=$?
          set -e

          # forge create doesn't generate broadcast directory, just check exit code
          echo "Forge create completed with exit code: $rc"
          if [ $rc -eq 0 ]; then
            echo "✅ Forge create succeeded - contract deployed successfully"
            exit 0
          else
            echo "❌ Forge create failed with exit code: $rc"
            exit $rc
          fi

      - name: "Verify contract (optional)"
        run: echo 'Contract verification not implemented. Add forge verify-contract command here.'