name: Deploy Solidity
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: 'nightly'

      - name: Build Solidity contracts
        run: forge build --root ./agent-template

      - name: Deploy to Testnet/Mainnet
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          forge script script/Deploy.s.sol:Deploy --rpc-url $RPC_URL --private-key $PRIVATE_KEY --broadcast --verify --root ./agent-template

      - name: Verify contract (optional)
        run: |
          # Example verification command (adjust based on your needs)
          # forge verify-contract --rpc-url $RPC_URL --verifier etherscan <contract_address> <contract_path>:<contract_name>
          echo 'Contract verification not implemented. Add forge verify-contract command here.'
