name: Publish to npm

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      force_publish:
        description: 'Force publish even if version exists'
        required: false
        default: false
        type: boolean

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Check if version already published
        id: check-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          # Retry npm view a few times to account for registry replication delays
          attempts=0
          max_attempts=5
          published=false
          while [ $attempts -lt $max_attempts ]; do
            if npm view somnia-ai-agent-cli@$VERSION version >/dev/null 2>&1; then
              published=true
              break
            fi
            attempts=$((attempts+1))
            sleep $((attempts * 2))
          done

          if [ "$published" = true ]; then
            echo "Version $VERSION already published"
            echo "should-publish=false" >> $GITHUB_OUTPUT
          else
            echo "Version $VERSION not published yet"
            echo "should-publish=true" >> $GITHUB_OUTPUT
          fi

      - name: Publish to npm
        if: steps.check-version.outputs.should-publish == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public